# Generated by Django 4.0.1 on 2024-07-20 09:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 20, 9, 22, 33, 982024, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
