# Generated by Django 4.0.1 on 2024-07-20 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_name_category_cat_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_name',
            new_name='name',
        ),
    ]
